spring:
  application:
    name: timetable-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/keycloak}
    username: ${SPRING_DATASOURCE_USERNAME:keycloak}
    password: ${SPRING_DATASOURCE_PASSWORD:keycloak}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/timetable-realm}

keycloak:
  token-url: ${KEYCLOAK_TOKEN_URL:http://localhost:8181/realms/timetable-realm/protocol/openid-connect/token}
  client-id: ${KEYCLOAK_CLIENT_ID:timetable-backend}

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health,info


